### ISSUE TITLE
automake fails: config.h.in missing

### ISSUE THREAD

**Issue by umeding** [logological/gpp#31]
When building from scratch I get the following error:

$ automake -a
configure.ac:12: installing './compile'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
Makefile.am: installing './INSTALL'
**configure.ac:9: error: required file 'config.h.in' not found**
src/Makefile.am: installing './depcomp'

When line 9 is commented out, everything works fine from there on out: gpp compiles fine, and runs fine.

**Comment by logological** [comment]
That is not how you are supposed to build an Autotools project from scratch.

If all you are interested in is building from source, then download [the source release](https://github.com/logological/gpp/releases) and follow the instructions in the `INSTALL` file.  (For most Unix-like systems, this will be some variant of the the standard `./configure && make && sudo make install` invocation.)  At no time will you ever need to run `automake`.

If you want to actually do development work and need to mess around with the Autotools configuration, then you should clone the source repository and run the usual Autotools toolchain.  This will probably be some variant of `aclocal && autoheader && automake --add-missing && autoconf` followed by the build instructions mentioned above.
