### ISSUE TITLE
config.h.in missing

### ISSUE THREAD

**Issue by Coding-Badly** [logological/gpp#33]
config.h.in is missing from this repository and the release assets.  According to the INSTALL file config.h.in is necessary to build on Windows.  Which appears to be true.

**Comment by logological** [comment]
I downloaded the release assets just now and `config.in.h` is present for me.  Could you be more specific as to what release you are downloading and how you're unpacking and building it?

**Comment by Coding-Badly** [comment]
Start here...
https://github.com/logological/gpp

Click "10 releases" which navigates here...
https://github.com/logological/gpp/releases

Click "Source code (zip)" which downloads a file named...
gpp-2.25.zip

Open the file with the latest version of 7-Zip.

Extract the folder gpp-2.25 to a temporary location.

Check for files named "config"...
> dir *config* /s /b
configure.ac

configure.ac is not config.in.h.

**Comment by Coding-Badly** [comment]
Navigate to the file finder...
https://github.com/logological/gpp/find/master

Enter the filename...
config.h.in

No matching files found.

**Comment by logological** [comment]
> Click "Source code (zip)" which downloads a file named...
> gpp-2.25.zip

This is the problem—that ZIP file is not the real source distribution.  This is just a copy of the tagged revision of the source repository.  GitHub automatically creates this and stupidly adds it to the release assets.  I don't think there is anything I can do to suppress this.  The real source distribution (i.e., the one packaged by Autotools) is the tarball `gpp-2.25.tar.bz2`.

Could you please try downloading and unpacking the tarball and verify that it builds for you on Windows?  I don't use Windows myself so it is not easy for me to check.

**Comment by Coding-Badly** [comment]
> This is the problem...

Nope.  The problem is that the project cannot be built from a cloned repository on a Windows computer.  A sample config.h needs to be included in the repository.

> I don't think there is anything I can do to suppress this.

Suppressing is not necessary.  Fix the missing config.h file problem and the ZIP file will be usable.

**Comment by logological** [comment]
> Nope. The problem is that the project cannot be built from a cloned repository on a Windows computer.

The project can't be built from a cloned repository on _any_ computer.  This is by design.  Please use the Autotools-packaged source distribution.

**Comment by Coding-Badly** [comment]
Which defeats the purpose of having Git repository.  No thanks.

I'll just work against my fork.  I've already wasted too much of my time trying to convince you the missing file is a problem.
