### ISSUE TITLE
How to install gpp on CentOS

### ISSUE THREAD

**Issue by malcolm061990** [logological/gpp#37]
How to install gpp on CentOS?
I can't find rpm package for this OS.

**Comment by logological** [comment]
I'm not aware of any binary packages for CentOS.  Maybe you can contact the maintainers and suggest that they include it in the distribution.  In the meantime, you can manually compile and install GPP from the portable source packages as described on the GPP home page and in the README on GitHub.

**Comment by malcolm061990** [comment]
> I'm not aware of any binary packages for CentOS. Maybe you can contact the maintainers and suggest that they include it in the distribution. In the meantime, you can manually compile and install GPP from the portable source packages as described on the GPP home page and in the README on GitHub.

But in master branch there is no INSTALL file for some reason.
In 2.25 tag this file exists.

**Comment by logological** [comment]
The master branch is not the portable source package.  If all you want to do is compile and install the software, use the portable source package.

**Comment by malcolm061990** [comment]
Thanks. I compiled it using 2.26 tag.
