### ISSUE TITLE
There is no INSTALL file

### ISSUE THREAD

**Issue by drj11** [logological/gpp#38]
Per my review at https://github.com/openjournals/joss-reviews/issues/2400

For installation your README says "see the included INSTALL file." but there is no `INSTALL` file.

**Comment by logological** [comment]
The INSTALL file is automatically generated by the GNU Autotools when they produce the portable source packages.  As a generated file, it is not checked into the source repository.  If you download the portable source packages, you can verify that the file exists there.

**Comment by drj11** [comment]
Yes, that is what I'm doing now. In which case that's fine for the purposes of review, but I would encourage you to mention this fact in the README. The README does mention that you can clone the github repo, but perhaps it should not. Or it should say that cloning is only recommended for developers or people willing to get familiar with autotools.

**Comment by logological** [comment]
OK, I will make the README a bit more explicit in this respect.
