### ISSUE TITLE
Define a macro to include file not working

### ISSUE THREAD

**Issue by drriguz** [logological/gpp#60]
Hi,
I'd like to define a macro to include files dynamically, here's a minimal example:

File structure:
```
- main.txt
\ chapters
  - ch01.txt

```

main.txt
```
#define IMPORT(dir,file) #include dir/file

#include chapters/ch01.txt
IMPORT(chapters, ch01.txt)
```

Then I run `gpp main.txt`, 
`#include chapters/ch01.txt` works as expected,
However, the last line, `IMPORT(chapters, ch01.txt)` won't work, and says that `error: Requested include file not found`.

It's this a bug or it's something that not supported?

Thanks,
Riguz

**Comment by logological** [comment]
As explained in the manual, arguments to meta-macros (like `#include`) aren't necessarily evaluated.  The Examples section explains how to get around this using `#defeval` and some helper macros.  (See in particular the examples involving the macro `APPLY`.)  Here's how you might adapt it to your particular use case:

```
#define IDENTITY(x) x
#define IMPORTSTRING(dir,file) \#include dir/file
#define IMPORT(dir,file) IDENTITY(#defeval TEMP IMPORTSTRING(dir,file)
TEMP)

IMPORT(chapters,ch01.txt)
```

Does this solve your problem?

**Comment by drriguz** [comment]
Yes, it works! Thanks for your help!

It's a little bit hard to get startted, thought it's actually already explained in detail in the manual. A toturial should be helpful for beginners like me :p

**Comment by logological** [comment]
OK, glad I could help!  I agree that a tutorial would be nice.  I don't have the time to produce one now but perhaps someone else might step up and volunteer. :)
